### ISSUE TITLE
i am very sorry

### ISSUE THREAD

**Issue by Lickyyy** [WowItsKaylie/CustomCOC#1]
i had no idea that u had a github for the coc thing i removed it from my github and i hope you can forgive me (i didnt make the discription my friend made it (cxz) )

i have learned to not do it again bc it will lead to getting banned in servers and i really hope that you can forgive me and that you can understand that i didn't know that you started the CustomCOC and i just thought that you did it because you were bored

**Comment by gizmogoat** [comment]
ok

**Comment by Lickyyy** [comment]
ok
